version: 2

orbs:
  maven: circleci/maven@0.0.12

workflows:
  maven_test:
    jobs:
      build:
        environment:
          CODECOV_TOKEN="e40eac21-f4da-4600-bd61-3a379874f8e4"
        steps:
          - checkout
          - run: mvn test
          - run:
              name: Export test coverage to codecov
              command: bash <(curl -s https://codecov.io/bash)
          - store_artifacts:
              path: target
